name: Update Website

on:
  push:
    branches:
      - main  # 监听 main 分支的推送
  schedule:
    # 每小时触发一次（也可以删除这个部分，仅通过 push 触发）
    - cron: '0 * * * *'
  workflow_dispatch: # 手动触发工作流

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 设置 Python 版本（根据需求调整）

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt  # 安装依赖（确保你的依赖在 requirements.txt 中）

    - name: Run the Python Script
      run: |
        python update_website.py  # 执行更新脚本

    - name: Checkout gh-pages Branch
      run: |
        git fetch origin gh-pages  # 获取 gh-pages 分支的最新内容
        git checkout gh-pages  # 切换到 gh-pages 分支

    - name: Commit and Push Changes to gh-pages
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add index.html  # 确保 index.html 被添加
        git commit -m "Auto update index.html"
        git push origin gh-pages  # 推送到 gh-pages 分支
