name: Update Website

on:
  schedule:
    - cron: '0 * * * *'  # 每小时的第 0 分钟执行，即整点执行

  push:
    branches:
      - main  # 只要 main 分支有更新，自动触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas  # 安装任何需要的依赖项

    - name: Run Python script to generate website
      run: python update_website.py  # 运行您的 Python 脚本生成网页内容

    - name: Push website files
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add -A  # 添加所有更改
        git commit -m "Update website"
        git push 
