name: Update Website

on:
  schedule:
    - cron: '0 * * * *'  # 每小时的第 0 分钟执行
  push:
    branches:
      - main  # 只要 main 分支有更新，自动触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install akshare

    - name: Run Python script to generate website
      run: python update_website.py  # 运行你的 Python 脚本
    
    - name: Deploy to gh-pages
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        
        # 获取并切换到 gh-pages 分支
        git fetch origin gh-pages
        git checkout gh-pages || git checkout --orphan gh-pages  # 如果没有 gh-pages 分支则创建
    
        # 存储当前更改，避免在切换分支时丢失
        git stash || echo "No changes to stash" 
    
        # 切换回 main 分支并确保获得最新的 index.html
        git checkout main
        git pull origin main  # 拉取最新的 main 分支，确保获得最新的 index.html
    
        # 强制复制 index.html 文件到 gh-pages 分支
        cp -f index.html ./  # 使用 -f 强制覆盖文件
    
        # 提交并推送更改
        git add -A
        git commit -m "Update website"
        git push origin gh-pages

