name: Update Website

on:
  push:
    branches:
      - main  # 你可以根据需要更改为主分支

jobs:
  update-website:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 可以根据需要修改 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas  # 安装 pandas，确保 Python 脚本能运行

    - name: Run Python script to update website
      run: python update_website.py

    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add index.html
        git commit -m "Update website with new ranking"
        git push
