name: Update Website

on:
  schedule:
    - cron: '0 * * * *'  # 每小时的第 0 分钟执行
  push:
    branches:
      - main  # 只要 main 分支有更新，自动触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install akshare

    - name: Run Python script to generate website
      run: python update_website.py  # 运行你的 Python 脚本

    - name: Deploy to gh-pages
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        
        # 拉取 gh-pages 分支并切换
        git fetch origin gh-pages
        git checkout gh-pages || git checkout --orphan gh-pages  # 如果没有 gh-pages 分支则创建
    
        # 复制生成的 index.html 文件到当前目录，确保更新
        cp index.html ./  # 不做文件是否存在的检查，直接覆盖
    
        # 提交更新并推送
        git add -A
        git commit -m "Update website" || echo "No changes to commit"
        git push origin gh-pages

        git add -A
        git commit -m "Update website"
        git push origin gh-pages
